### ISSUE TITLE
RSS Feed ingestion not triggering Watson NLU tagging

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#123]
**Describe your question**
In chatting with @dingman, their site scenario is based more on content ingestion via RSS feeds using the [WordPress Automatic Plugin](https://codecanyon.net/item/wordpress-automatic-plugin/1904470) and a cron job.  This posting of content does not appear to trigger  sending the content to Watson for Language Processing as no tags appear on content regardless how low the thresholds are, but manually updating the content gets the tags to appear.  Potential issue here is that the WP Automatic plugin doesn't use the same hooks that ClassifAI does, so can we confirm to @dingman what hook(s) ClassifAI uses to compare with WP Automatic?

**Comment by dinhtungdu** [comment]
@dingman can you please confirm/give me some information about how WordPress Automatic Plugin works? I tried their demo today but I still need to know how it works internally to debug this issue. Can we have a chat/email about this?

**Comment by dingman** [comment]
Hey @dinhtungdu sure we can, Jeff has my contact information.

specifically what I think would be the first place to start, is that the WP Automatic plugin is running via cron jobs and not usually from the dashboard. So being able to look at its hooks and detect this plugin, and any others, would be running the publish_post or save_post hook

**Comment by jeffpaul** [comment]
@dingman do you have details on where WP Automatic hooks in?

**Comment by jeffpaul** [comment]
As we're looking to release v1.5.0 in the next week or so and with no linked PR for this issue, I'm going to move this to `Future Release` until we're able to confirm details on this issue and work up a PR for it.

**Comment by dingman** [comment]
I believe it's in the save_post hook

https://developer.wordpress.org/reference/hooks/save_post/

It could be others as well, but that's at least one of them

**Comment by s3rgiosan** [comment]
@jeffpaul 
I did some investigation and the issue is related to the `SavePostHandler` class registration that happens [here](https://github.com/10up/classifai/blob/develop/includes/Classifai/Providers/Watson/NLU.php#L126=). If we take a closer look at the `can_register` [function](https://github.com/10up/classifai/blob/develop/includes/Classifai/Admin/SavePostHandler.php#L26), we see that the class is only registered when it's running on the admin or REST requests.
(Btw, I simplified the logic behind the class registration [here](https://github.com/10up/classifai/pull/341))

The WordPress Automatic plugin runs the campaign processor through a cron job, even when the "Run campaign" button on each campaign is clicked, and the ClassifAI `SavePostHandler` is not registered (instantiated) when that happens.

We have some possible solutions here.

- Adding `(defined( 'DOING_CRON' ) && DOING_CRON )` as a condition to register the handler. But since we're not doing this for WP_CLI scripts, I'm not sure if this is the best approach.

```
public function can_register() {

	if (
		is_admin()
		|| $this->is_rest_route()
		|| ( defined( 'DOING_CRON' ) && DOING_CRON )
	) {
		return true;
	}

	return false;
}
```

- Adding a hook that other developers can use to add more registration conditions, like this case of the WordPress Automatic plugin. Something like:

```
public function can_register() {

	$should_register = false;

	if (
		is_admin()
		|| $this->is_rest_route()
	) {
		$should_register = true;
	}

	/**
	 * Filter whether ClassifAI should register this class.
	 *
	 * @since 1.8.0
	 * @hook classifai_should_register_save_post_handler
	 *
	 * @param  {bool} $should_register Whether the class should be registered.
	 * @return {bool} Whether the class should be registered.
	 */
	$should_register = apply_filters( 'classifai_should_register_save_post_handler', $should_register );

	return $should_register;
}
````

And then, in the theme `function.php` file, for example:
```
function classifai_register_save_post_handler( $should_register ) {

	if ( defined( 'DOING_CRON' ) && DOING_CRON ) {
		return true;
	}

	return $should_register;
}
add_filter( 'classifai_should_register_save_post_handler', 'classifai_register_save_post_handler' );
```

Let me know your thoughts.

**Comment by jeffpaul** [comment]
@dkotter any preference on optimal approach on options above?

**Comment by dkotter** [comment]
I think we should do the second approach for sure, as this gives developers the flexibility to fine tune this even further.

I'm not opposed to also supporting cron by default but as mentioned, since we're already not supporting WP-CLI, I think we may be best leaving out cron support and people can add that themselves with the new filter.

**Comment by s3rgiosan** [comment]
Thanks @dkotter @jeffpaul. I've updated the PR https://github.com/10up/classifai/pull/341, and it's ready for review at your earliest convenience.
