### ISSUE TITLE
Ability to remove tags without ClassifAI immediately re-adding them back

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#185]
**Is your enhancement related to a problem? Please describe.**
There currently is no way within ClassifAI to remove tags on posts/pages.  If you try to do so and then save that post/page, then ClassifAI will simply re-send that post/page off and likely re-apply the removed tag via IBM Watson.  The only "option" would be to deactivate ClassifAI, make those changes, and then re-activate ClassifAI; but that's clearly sub-optimal.

**Describe the solution you'd like**

We could add an on/off toggle in a metabox in the Classic Editor and potentially within a Gutenberg slotfill that would allow someone to save/publish/update without sending the content to Watson.  This seems like the simplest approach, but likely warrants some UX/design to ensure we're handling this as gracefully as possible.

**Designs**

TBD, but needed.

**Describe alternatives you've considered**

None, keeping as-is is not ideal.

**Additional context**

None.

**Comment by helen** [comment]
After discussing this, here's a solution I think could work: display but disable the taxonomy sections and alt text field and add some kind of UI (maybe a checkbox or an edit "link"/button) that lets the user know that they can go ahead and edit the specific field in question but from that point forward it will no longer update said field from ClassifAI. A checkbox type of toggle could be nice so that you could opt back into updating from ClassifAI later.

Another potential solution that is probably unpleasant to implement would be to track items removed and not add them back with new responses unless you un-remove them, whatever that entails.

**Comment by jeffpaul** [comment]
I wildly prefer the former to the later @helen, the later just sounds unwieldy and nightmarish (not unlike parenting hangry children in a car miles away from the nearest food source).

**Comment by Vidyut** [comment]
I too would like a good fix for this. Something like getting tags only if the tags field is empty should do the trick. If anyone wants to specifically auto tag something that is already tagged, they can simply copy the tags for backup if needed and delete them from the post and the plugin can do its thing and populate the tags again. 

Probably will be simplest to implement - if empty process, if not empty, leave alone.

At the moment, I'm using the Watson categories, watson keywords, etc taxonomies without displaying them and letting the plugin do what it wants, and then the terms that look suitable get taxonomy changed to tags that I use on the blog. It is primitive, but displaying the terms the plugin comes up with is not an option for me right now, because removing unsuitable terms simply adds them right back.

**Comment by jeffpaul** [comment]
@helen what do you think of @Vidyut's suggestion that ClassifAI only processes the content for tagging if there are no tags on the content in the taxonomies selected in the ClassifAI settings (noting that not everyone dumps things into actual `Tags`)?  We could add a similar button/link to "retag content" in the sidebar/metabox similar to how we handle image processing to allow someone to forcibly re-tag content even if tags are present.

**Comment by iamdharmesh** [comment]
> ClassifAI only processes the content for tagging if there are no tags on the content in the taxonomies selected in the ClassifAI settings

@jeffpaul I think with this approach, the content will get processed only once. and post author has to click the "retag content" button every time to get content processed. _for example, Post author has created a post with 1 paragraph and clicked `Save`, ClassifAI has generated related tags based on content. now if the author adds more content to the post and saves it, then tags will not get generated because the post already has tags_. and I think we get more accurate tags based on the latest content of post. 

So, As requested in the initial request, adding a toggle to enable/disable looks more suitable to me.

**Comment by iamdharmesh** [comment]
Hi @jeffpaul , 

Can I proceed on this with an on/off toggle in Gutenberg slot fill and meta box in the Classic Editor?

**Comment by jeffpaul** [comment]
@iamdharmesh as discussed today, please proceed and I'll check in when you have a reviewable reference point on implementation... thanks!
