### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [10up/classifai#335]
Is your enhancement related to a problem? Please describe.

Once WordPress 6.0 is released, we'll want to test ClassifAI to see if any incompatibility issues arise.

Describe the solution you'd like

  

- [ ] test ClassifAI on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #324, https://github.com/10up/classifai/issues/205, https://github.com/10up/classifai/issues/261. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
I've been testing this on 6.0 for the last couple of days.

Intermittently one of the custom taxonomy endpoints is returning a 404 error and I am unable to determine why. This cause the block-editor to crash (see https://github.com/WordPress/gutenberg/issues/41095).

I've not seen this happen on any other plugins so for now I think it's best to wait before declaring WP 6.0 support. I'll come back to this to continue on a reduced test case to determine if it's a WP or plugin bug.

**Comment by peterwilsoncc** [comment]
Testing notes

- Created install on public facing web server for testing with
- Set up API keys

**Comment by peterwilsoncc** [comment]
@lukaspawlik I actually tested this a few weeks ago but was waiting for the Gutenberg bug I linked to in the comment above to be merged before marking it 6.0 ready. That's since happened so I will push a branch.

Testing notes
* tested on public facing web server to allow bots access
* Set confidence levels to `zero` for all fields so any results would populate the fields
* Images
   - Uploaded a random image of [Ben Platt standing on a stage](https://www.broadway.com/buzz/197037/will-ben-platt-reprise-his-tony-winning-performance-in-the-dear-evan-hansen-movie/).
   - Alt text generated: Ben Platt standing on a stage
   - multiple tags created including: human man, face, clothing, person
   - no text generated for caption
   - Uploaded image containing text: text added to caption (incorrect but the bot was confused)
   - Uploaded multi-page PDF containing text: added to caption (correct)
* Posts
  - Enabled all three custom taxonomies
  - Watson created and populated them as expected

There are some intermittent 404s on the custom taxonomy endpoints I am seeing but that appears to be an existing bug independent of WP version
