### ISSUE TITLE
Content Generation

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#398]
### Is your enhancement related to a problem? Please describe.

There are a couple cases for content generation we could consider:
- [ ] generate post content from simple input/bullet points/prompts
https://sassbook.com/ai-text-generator-api could be a useful option to consider here

- [x] generate (featured) image from simple input/bullet points/prompts

### Designs

It would be helpful to gather a list of services that could be of use here to determine which might be the best fit within ClassifAI and for the WordPress community

### Describe alternatives you've considered

Other plugins in the WP space may already implement some/all of this functionality, so there's some question to the value of adding this into ClassifAI though if we can find a more affordable AI service or integrate a different AI service then that at least provides alternatives for folks to consider to what may already be available in the market.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TylerB24890** [comment]
I think it makes a lot of sense to implement something like this into ClassifAI. It would almost bring the plugin to a more full-service authoring system and would compliment the existing tagging and image classification quite well. Even if it were developed as an installable extension.

I did a little bit of research on potential services that could be considered here. There's a combination of services that can handle both text & image generation and services that handle one or the other.

- https://openai.com/product - Probably the most popular due to ChatGPT. Text and Image generation [via API](https://rapidapi.com/mnai01/api/openai37/?utm_source=google&utm_medium=cpc&utm_campaign=DSA&utm_term=_).
- https://writer.com/product/api/ - Text and Image generation via API.
- https://textcortex.com/text-generation-api - Text and Image generation via API.
- https://www.ai21.com/studio - A more barebones API service for text generation.
- https://monsterapi.ai/ - Image generation only.
- https://www.jasper.ai/ - Not yet available. "AI Copywriter" can write content _and_ generate images. The API has a sign-up page with "Coming soon" across the top. Not too sure on the status of it.

I'll continue thinking about this and will follow up again if I come across anymore services or ideas.

**Comment by dkotter** [comment]
Image generation was added in #419 using OpenAI. Could look to add other providers if desired.

**Comment by jeffpaul** [comment]
On the text generation front, similar to how we have an image generation credit and license in the caption of generated images, I'd like to see us include a block at the bottom of any post where ClassifAI generates content that effectively adds a source/footnote sort of reference as to the provenance of (at least some, if not all) the post content.  So something like:
> _Source: <a href="https://openai.com/product/chatgpt">OpenAI's ChatGPT</a> was utilized during the creation of this post and is licensed as <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>._

The AI API could differ from ChatGPT and the proper license may differ from CC BY 4.0, so having some flexibility in those based upon our ultimate integration should be considered.  It's also feasible that the AI API will not come with a prescriptive license to apply so that might be something that's part of the service/feature onboarding flow in ClassifAI to select the license that applies to the generated content (we could have a list of possible options to consider, an option to enter an alternate license, as well as the ability to remove the licensing portion of the "source" block at the bottom of the post).

**Comment by jeffpaul** [comment]
Related: [How to cite ChatGPT](https://apastyle.apa.org/blog/how-to-cite-chatgpt)

**Comment by jeffpaul** [comment]
Closing this via #419
