### ISSUE TITLE
Fatal Error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given

### ISSUE THREAD

**Issue by prodport** [10up/classifai#472]
### Describe your question

I'm not a developer so this error could be from my configuration. On a staging site, I configured the plugin to use IBM Watson and Open AI. If I go to edit a post, I get this error message.

`Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-content/plugins/classifai-develop/includes/Classifai/Providers/OpenAI/ChatGPT.php:96 Stack trace: #0 /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-content/plugins/classifai-develop/includes/Classifai/Providers/OpenAI/ChatGPT.php(96): array_merge() #1 /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-includes/class-wp-hook.php(308): Classifai\Providers\OpenAI\ChatGPT->enqueue_editor_assets() #2 /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #3 /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-includes/plugin.php(517): WP_Hook->do_action() #4 /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-admin/edit-form-blocks.php(272): do_action() #5 /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-admin/post.php(187): require('/home/q8wmroe/p...') #6 {main} thrown in /home/q8wmroe/public_html/q8wmaqc4h1-staging.onrocket.site/wp-content/plugins/classifai-develop/includes/Classifai/Providers/OpenAI/ChatGPT.php on line 96`

If I use the Health Checkup Plugin, I can see Language Processing: IBM Watson and Language Processing: OpenAI ChatGPT as either configured or authenticated. I didn't elect any of the other tools.

Version: 2.2.1-dev
Valid license: yes
WP Version: 6.2.2
Server architecture: Linux 4.18.0-425.3.1.lve.3.el8.x86_64 x86_64
Web server: Apache
PHP version: 8.0.28 (Supports 64bit values)

![image](https://github.com/10up/classifai/assets/12213481/0344e73d-52f1-48e6-8490-bc4bfb14028a)

Any idea how to get past this issue?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@prodport Thanks for the question!

Looking at the error log, it seems you've installed ClassifAI from the `develop` branch. That's fine but there are a few extra steps that need to be taken to build the plugin, namely:

`composer install && npm install && npm run build`

This will add some required dependencies and more importantly, will build all of our assets (javascript and CSS files). The error you're getting is because those assets haven't been built and thus can't be found. While those assets are needed for things to work, this does shine light on an area that we could handle more gracefully (instead of throwing an error) so I'll look to get that fixed up (thanks for pointing it out!).

Now if you'd prefer to not have to build those assets yourself, there are a few better approaches:

1. Clone the repo from the [`stable`](https://github.com/10up/classifai/tree/stable) branch, as this branch should be 100% built 
2. Download a zip from the [latest release](https://github.com/10up/classifai/releases/tag/2.2.0)
3. Register on [ClassifAIPlugin.com](https://classifaiplugin.com/) and we'll send you an email with a link to the latest zip

Let me know if you have any other questions or run into any other setup issues. Thanks!

**Comment by prodport** [comment]
Thanks. New version worked.
