### ISSUE TITLE
Add a filter hook to switch role between 'user' and 'system'

### ISSUE THREAD

**Issue by Sidsector9** [10up/classifai#550]
### Is your enhancement related to a problem? Please describe.

In PR #544 and #545 we changed the `role` parameter from `user` to `system`.
As per the feedback for [this comment](https://github.com/10up/classifai/pull/545#pullrequestreview-1554063642), we can allow the admin to choose the role.

We have 2 ways we approach this:

1. Add a filter hook
2. Add an admin setting

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
So personally I'd like to avoid adding settings wherever possible. In addition, this wouldn't be the easiest thing to describe in a setting, so I'd lean towards the filter approach.

That said, we already have a filter around the POST body (`classifai_chatgpt_excerpt_request_body` and `classifai_chatgpt_title_request_body`), so I'd almost say that those are good enough to solve this.

We have an existing issue open (#475) to start adding snippets to our automated docs. If we agree these existing filters are good enough to solve the problem here, these are probably a good candidate for that documentation

**Comment by Sidsector9** [comment]
I agree, in that case I'll close this issue.
