### ISSUE TITLE
Update required in ClassifAI plugin registration email content.

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/classifai#564]
### Is your enhancement related to a problem? Please describe.

The email sent to customers post ClassifAI plugin registration contains outdated information pertaining to the 'Requirements' section.

1. As per the [GitHub readme](https://github.com/10up/classifai#requirements), the minimum requirements are as follows:

- Minimum PHP version: 7.4+
- Minimum WordPress version: 5.7+

The email has the following:

- Minimum PHP version: 7+
- Minimum WordPress version: 5.0+

2. Now ClassifAI also provides features related to OpenAI. So would be great if add the reference of OpenAI in email content.

### Designs

| Email | Readme |
|--------|--------|
| ![image](https://github.com/10up/classifai/assets/6384299/87b49bf7-80ee-4c15-9805-77fb21024382) | ![Screenshot 2023-08-11 at 8 26 33 PM](https://github.com/10up/classifai/assets/6384299/ff132a14-aac6-47ca-ad84-71319bb50a2f) | 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
IMO we should completely remove the minimum required versions from the email template since users will see the warning when they install the plugin anyway.

https://github.com/10up/classifai/blob/1179e74b50899371f5527440d88de0809fed9ccc/classifai.php#L46-L50

If we want to inform users about the requirements before they install the plugin, we can remove the version numbers and provide a link to the [GitHub README](https://github.com/10up/classifai#requirements), where they can find the minimum requirements. This approach will prevent the need to update these versions in email template with every version bump. cc @jeffpaul

**Comment by faisal-alvi** [comment]
Also, I think we should remove the required active accounts list from the email template,

```
...an active account from the respective service provider for the functionality in-use: Microsoft Azure, IBM Watson, or OpenAI.
```

as it seems obvious that users would need specific accounts to use their respective services via the ClassifAI plugin. Alternatively, instead of completely removing this information, we could mention it more generally. For example, as @iamdharmesh suggests, we could state

> ...an active account from the respective service provider for the functionality in-use would be required.

**Comment by jeffpaul** [comment]
@faisal-alvi works for me, can you make those changes and then mark this issue as closed when that's done?

**Comment by faisal-alvi** [comment]
MR raised: https://gitlab.10up.com/10up-public-sites/oss-projects.10up.com/-/merge_requests/107
