### ISSUE TITLE
Adjust handling of Language Processing's flow for classifying posts

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#566]
### Is your enhancement related to a problem? Please describe.

As an alternate to #530, we could add a new button in the sidebar for "Classify Post":
![ClassifAI_PostClassification_NewFlow_1-ClassifyPostButton](https://github.com/10up/classifai/assets/2818133/2161744c-6016-49ce-aeb4-5e94535b081f)

This mockup shows it next to the potential ClassifAI "Generate titles" button, but could also be in the "ClassifAI" sidebar panel or each of the "Categories", "Tags", etc. panels.

This would send the post content to Azure and display the returned classifications in a modal:
![ClassifAI_PostClassification_NewFlow_2-ConfirmPostClassifcationModal](https://github.com/10up/classifai/assets/2818133/3fa6b0d9-3eb5-452f-a425-e11cb2b55574)

Someone could then add/remove the classifications and then save when the data from Azure meets expectations.

As a final catch, if there are no classifcations the Pre-Publish Panel could add a "Suggestion: Classify post" section:
![ClassifAI_PostClassification_NewFlow_3-PrePublishPanel](https://github.com/10up/classifai/assets/2818133/a739324c-2c22-4b98-a0c5-1107730faea5)

Someone could then add/remove the classifications and then save when the data from Azure meets expectations.

### Designs

Here's how the current post classification flow works:
https://github.com/10up/classifai/assets/2818133/f0d13446-aad4-42eb-8df2-e4b8dca4f254

Essentially you get the categories/tags/etc. applied after publishing a post (or whatever post statuses are enabled in settings) with the ability to toggle on/off updates via a sidebar setting in the ClassifAI post sidebar section.

### Describe alternatives you've considered

See #530.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@jeffpaul @dkotter 

In the current workflow, terms retrieved from the response are initially stored in the database and then presented in the dropdown.

I have a few concerns with the new design shared above. The pop-up modal, which includes the core taxonomy dropdown blocks, displays terms, but actually, those terms will be already saved in order to display in the dropdown. On the other hand, the requirement is to allow users to decide whether they want to save a term or not. We cannot display the terms in the dropdown until they are saved, which is a challenge.

To address this, we may need to avoid integrating the dropdown like the core blocks and instead develop a custom component. This custom component would present the keywords received from the response in a modal. Each keyword would be accompanied by a checkbox (defaulted to checked), allowing users to uncheck those they do not wish to add. Only the checked terms would be saved. (Same applies to Pre-Publish Panel)

<img width="603" alt="image" src="https://github.com/10up/classifai/assets/25176325/ba960b84-a72b-4d1b-982d-210edfbcdafa">

However, in this custom layout, users would be unable to add new terms or select existing ones that are not listed in the popup. To perform such actions, users would need to close the popup and make their selections from the right sidebar.

Please share your thoughts.

**Comment by dkotter** [comment]
> To address this, we may need to avoid integrating the dropdown like the core blocks and instead develop a custom component

I don't think we are set in stone on this UI so definitely open to thoughts on a better approach.

> Each keyword would be accompanied by a checkbox (defaulted to checked), allowing users to uncheck those they do not wish to add. Only the checked terms would be saved.

This sort of UI makes sense to me, though I'd love to hear what @jeffpaul's thoughts are on that

That said:

> The pop-up modal, which includes the core taxonomy dropdown blocks, displays terms, but actually, those terms will be already saved in order to display in the dropdown

I don't know if this is too much of a concern (the idea that we need to create these terms to show them). The bigger issue is not associating a term with a post until a user has reviewed. So we could create the terms, show them in this UI and allow a user to choose which terms they want, which then associates those terms with the post. Any terms they don't select we could then delete those terms.

**Comment by jeffpaul** [comment]
Sharing a rough mockup from my call with @faisal-alvi today on potential modal experience:

![Faisal-JP 1_1 2023-10-31 09_43 AM Page-1- 1698764702570](https://github.com/10up/classifai/assets/2818133/5e10db21-85d2-4d4c-ae46-3f46269c987c)
