### ISSUE TITLE
Threshold value for Embeddings

### ISSUE THREAD

**Issue by timatron** [10up/classifai#577]
### Is your enhancement related to a problem? Please describe.

I am using classifai to provide suggestions to our editorial team for adding categories and tags to post as well as reapplying cats and tags to all of our posts for a big migration. The main problem i've found with embeddings is false positives when applying categories automatically in our migration, it would be great if you could add a threshold value to the embeddings, so that not all cats or tags get applied, but only ones that are highly relevant. This is already done in the IBM Watson interface and seems possible based on my quick glance of the openai api. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Providing some additional information here based on our conversation this morning.

As part of their API, IBM Watson will return a confidence score for each item (a value between 0 and 1, closer to 1 means a better match). In our settings page, we allow you to set a threshold for each taxonomy (a percentage from 0 to 100) that maps to the score values the API will return. The way we handle this right now is we take the threshold value, [convert that to an integer](https://github.com/10up/classifai/blob/trunk/includes/Classifai/Helpers.php#L414) (so a 70% threshold will be converted to 0.7) and then [compare that against our results](https://github.com/10up/classifai/blob/trunk/includes/Classifai/Watson/Linker.php#L333), removing any that fall below that threshold.

In contrast, the OpenAI Embeddings API won't return any sort of score or threshold. It converts text into vectors and then we are using that data to run calculations. You can see the similarity function we run [here](https://github.com/10up/classifai/blob/trunk/includes/Classifai/Providers/OpenAI/EmbeddingCalculations.php#L20). This will return scores between 0 and 2, with items closer to 0 being the ones that are the most similar. While this is slightly different, I think we can mostly achieve the same thing by doing the following:

1. Add a new setting (or settings, if we want to add a threshold value for each taxonomy, which is what we do on the IBM Watson side) where a threshold value can be set. This should be a number between 0 and 100 and displayed as a percentage
2. When we [run our similarity calculation](https://github.com/10up/classifai/blob/trunk/includes/Classifai/Providers/OpenAI/Embeddings.php#L478) and before we assign terms, grab the threshold value, find the difference between that value and 100 (since closer to zero means more similar) and convert that into a decimal (so 70% becomes 30% which becomes 0.3)
3. Then remove any terms that aren't at or below that number, so in the example above, remove any terms that aren't 0.3 or below

As a maybe more helpful example, I ran this locally on a site with only 4 categories and got the following output after the similarity calculation was run:
```php
array(
    68 => 0.24485333996879444,
    73 => 0.25077597667429374,
    72 => 0.26137876645590863,
    51 => 0.26143541223049682,
)
```

The array key is the term ID and the value is the score. You can see that all these scores are pretty close to each other, though in my opinion, only term 68 was a good match (I think it was the News category).

I'd set a threshold of 75% (I think this should be our default to start). During the match process, we would subtract that from 100 and get 25%. We then divide that by 100 to get 0.25. We then would compare that against these scores and remove any that are greater than 0.25, which would leave us with only term 68 to assign.

The only other thing I'd note is we currently calculate scores between 0 and 2, whereas the above logic really only works for numbers between 0 and 1. In my testing I've never seen scores above 1 or really even close to 1 so I think this is fine (we may even look to adjust our calculations to be between 0 and 1 just to be safe).
