### ISSUE TITLE
Enabling features by Role/User

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#588]
### Is your enhancement related to a problem? Please describe.

In order to roll out and granularly control specific features to specific roles and users, we might best recommend applying role- and user-based access to individual features, and rearchitecting the way access is controlled (at the code level) with custom defined capabilities for each feature (e.g. “classifai_can_generate_titles”), making even more granular control and role management available to developers and “pro” administrators.

For the interface, an example like the below would be added, wherever it's currently not available on each ClassifAI feature settings page, that would allow for enabling role-based access and subsequently which roles should have access to the specific feature:

![new-role-access](https://github.com/10up/classifai/assets/2818133/7ebfc43d-df62-461f-93b0-55d51757d3a3)

An example like the below would also be added that would allow for enabling user-based access, a listing of specific users with access, and an option that would enable users to opt themselves out of a specific feature even if they are allowed access to it:

![new-user-access](https://github.com/10up/classifai/assets/2818133/44763eae-b5a9-42a4-8278-e6e173e8d3f2)

A simplified view of editing a specific user to enable/disable access to specific ClassifAI features could look something like this:

![edit-user](https://github.com/10up/classifai/assets/2818133/af0553d2-c53a-4b8d-8b2a-9198912e8012)

A simplified view of a user editing their own profile to opt-out of specific ClassifAI features could look something like this:

![new-user-profile](https://github.com/10up/classifai/assets/2818133/b77b742b-1a03-47f7-952d-1d9c8085a710)

Specific to each Assistive AI feature, an in-context option can be presented to users to allow them to disable a feature without having to navigate to their profile (e.g., ClassifAI recommending tags for a post via a modal would have a action link opposite any primary/secondary action buttons to allow a user to disable the feature so they’re not presented with tag recommendations in the future).

Finally within this batch of work would be ensuring that a capability exists for each ClassifAI feature to support the ability to enable capability-based access for users.

From a high-level estimation perspective, this will likely be a slightly larger effort (“t-shirt sized” L), will require adding additional settings to the Settings page, adding settings to the User profile page, and updating each feature to conditionally run depending upon these new settings with a rough estimate of 2-3 weeks for completion.

### Designs

See in-context in the description above.

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
A different design option (option 2) might look like this:

<img width="684" alt="image" src="https://github.com/10up/classifai/assets/25176325/cd9d7c4d-5b7b-40f7-b8a2-1fc0ce20ed24">

In this design, all the settings are consolidated on a single settings page, complete with a search bar. However, the drawback of this design is that administrators would need to visit individual setting pages for specific features to update related settings (e.g., prompts, etc).

**Comment by Sidsector9** [comment]
### Slack huddle summary: 1:1 Dharmesh

- The User profile page has a list of checkbox with features enabled for a user.
- For a site which have a lot of editors, it will be difficult to keep a track of features that are enabled for a particular user. In a situation where an admin decides that user A should have access to feature X _only_, they will first have to disable all the features that are already enabled for that user. So, toggling features from a User profile page makes it a lot more easier.
- Also for a user to opt in/out of that feature.

---

> a listing of specific users with access, and an option that would enable users to opt themselves out of a specific feature even if they are allowed access to it

From what I understand, the user profile feature settings and Classifai admin settings are independent of each other. Due to this, a feature will need to be enabled in 2 places for a user to use it.

#### Proposal to not allow a user to opt in/out a feature

A feature has (can have) role-based, username-based, etc access setting. Let's take an example of a user B who has an editor role. A feature X's role-based access is set to `editor`, `author`, and the username-based access is set to user B.

When a feature X is disabled for user B from the User profile page, technically the user should still have access to the feature because the feature is enabled for `editors`. If we go ahead with the initial plan, then we will have to clarify which access setting has precedence over the other.

IMO, we don't allow a user to opt-in/out from a feature. Semantically, configuring any kind of access levels should fall under the domain of a site admin/super-admin. I suggest – instead of providing checkboxes in the user profile page where the feature-access can be updated, we can list the features that are enabled for that user and provide hyperlinks for that feature's settings page.
This way, the site admin doesn't have to filter through all the features.

cc: @dkotter @jeffpaul
