### ISSUE TITLE
Add WordPress Playground integration

### ISSUE THREAD

**Issue by jeffpaul** [10up/classifai#797]
### Is your enhancement related to a problem? Please describe.

- [x] add blueprint to github folder
- [x] add repo badge to playground

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sidsector9** [comment]
@jeffpaul Since ClassifAI is not hosted on wp.org, do we want to add the Preview button to the repository?

If yes, then we have a blocker. WordPress Playground cannot download the plugin ZIP from Github as GH does not allow cross-origin requests.

None of the following URLs:
- https://api.github.com/repos/10up/classifai/zipball/stable
- https://github.com/10up/classifai/archive/refs/heads/stable.zip
- https://github.com/10up/classifai/archive/stable.zip

This is the error I am seeing:

<img width="1178" alt="Screenshot 2024-09-26 at 5 01 35 PM" src="https://github.com/user-attachments/assets/a8b7f28b-bdd0-4edf-9329-dbacd442ff45">

cc: @dkotter

**Comment by dkotter** [comment]
This was brought up in Distributor but seems we can use the https://github-proxy.com/ service to get around the problem. I've opened #814 to add this
